// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/messages.proto

package dtos

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN             MessageType = 0
	MessageType_GET_GAME_HISTORY    MessageType = 1
	MessageType_GET_GAME_LOBBIES    MessageType = 2
	MessageType_CREATE_LOBBY        MessageType = 3
	MessageType_JOIN_LOBBY          MessageType = 4
	MessageType_START_GAME          MessageType = 5
	MessageType_NEW_LOBBY_AVAILABLE MessageType = 6
	MessageType_PLAYER_JOINED_LOBBY MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "GET_GAME_HISTORY",
		2: "GET_GAME_LOBBIES",
		3: "CREATE_LOBBY",
		4: "JOIN_LOBBY",
		5: "START_GAME",
		6: "NEW_LOBBY_AVAILABLE",
		7: "PLAYER_JOINED_LOBBY",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":             0,
		"GET_GAME_HISTORY":    1,
		"GET_GAME_LOBBIES":    2,
		"CREATE_LOBBY":        3,
		"JOIN_LOBBY":          4,
		"START_GAME":          5,
		"NEW_LOBBY_AVAILABLE": 6,
		"PLAYER_JOINED_LOBBY": 7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

type CreateLobbyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPlayers    int32                  `protobuf:"varint,1,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyPayload) Reset() {
	*x = CreateLobbyPayload{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyPayload) ProtoMessage() {}

func (x *CreateLobbyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyPayload.ProtoReflect.Descriptor instead.
func (*CreateLobbyPayload) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLobbyPayload) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type JoinLobbyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyPayload) Reset() {
	*x = JoinLobbyPayload{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyPayload) ProtoMessage() {}

func (x *JoinLobbyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyPayload.ProtoReflect.Descriptor instead.
func (*JoinLobbyPayload) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *JoinLobbyPayload) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type StartGamePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGamePayload) Reset() {
	*x = StartGamePayload{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGamePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGamePayload) ProtoMessage() {}

func (x *StartGamePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGamePayload.ProtoReflect.Descriptor instead.
func (*StartGamePayload) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *StartGamePayload) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

type GetGameHistoryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameHistoryPayload) Reset() {
	*x = GetGameHistoryPayload{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameHistoryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameHistoryPayload) ProtoMessage() {}

func (x *GetGameHistoryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameHistoryPayload.ProtoReflect.Descriptor instead.
func (*GetGameHistoryPayload) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameHistoryPayload) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type NewLobbyAvailableEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	HostId        int64                  `protobuf:"varint,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	HostUsername  string                 `protobuf:"bytes,4,opt,name=host_username,json=hostUsername,proto3" json:"host_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewLobbyAvailableEvent) Reset() {
	*x = NewLobbyAvailableEvent{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewLobbyAvailableEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLobbyAvailableEvent) ProtoMessage() {}

func (x *NewLobbyAvailableEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLobbyAvailableEvent.ProtoReflect.Descriptor instead.
func (*NewLobbyAvailableEvent) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *NewLobbyAvailableEvent) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *NewLobbyAvailableEvent) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *NewLobbyAvailableEvent) GetHostId() int64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *NewLobbyAvailableEvent) GetHostUsername() string {
	if x != nil {
		return x.HostUsername
	}
	return ""
}

type PlayerJoinedLobbyEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LobbyId        string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerId       int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerUsername string                 `protobuf:"bytes,3,opt,name=player_username,json=playerUsername,proto3" json:"player_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerJoinedLobbyEvent) Reset() {
	*x = PlayerJoinedLobbyEvent{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinedLobbyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinedLobbyEvent) ProtoMessage() {}

func (x *PlayerJoinedLobbyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinedLobbyEvent.ProtoReflect.Descriptor instead.
func (*PlayerJoinedLobbyEvent) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerJoinedLobbyEvent) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *PlayerJoinedLobbyEvent) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerJoinedLobbyEvent) GetPlayerUsername() string {
	if x != nil {
		return x.PlayerUsername
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=dtos.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_CreateLobby
	//	*Message_JoinLobby
	//	*Message_StartGame
	//	*Message_GetHistory
	//	*Message_NewLobbyAvailable
	//	*Message_PlayerJoined
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetCreateLobby() *CreateLobbyPayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_CreateLobby); ok {
			return x.CreateLobby
		}
	}
	return nil
}

func (x *Message) GetJoinLobby() *JoinLobbyPayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_JoinLobby); ok {
			return x.JoinLobby
		}
	}
	return nil
}

func (x *Message) GetStartGame() *StartGamePayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_StartGame); ok {
			return x.StartGame
		}
	}
	return nil
}

func (x *Message) GetGetHistory() *GetGameHistoryPayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_GetHistory); ok {
			return x.GetHistory
		}
	}
	return nil
}

func (x *Message) GetNewLobbyAvailable() *NewLobbyAvailableEvent {
	if x != nil {
		if x, ok := x.Payload.(*Message_NewLobbyAvailable); ok {
			return x.NewLobbyAvailable
		}
	}
	return nil
}

func (x *Message) GetPlayerJoined() *PlayerJoinedLobbyEvent {
	if x != nil {
		if x, ok := x.Payload.(*Message_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_CreateLobby struct {
	CreateLobby *CreateLobbyPayload `protobuf:"bytes,2,opt,name=create_lobby,json=createLobby,proto3,oneof"`
}

type Message_JoinLobby struct {
	JoinLobby *JoinLobbyPayload `protobuf:"bytes,3,opt,name=join_lobby,json=joinLobby,proto3,oneof"`
}

type Message_StartGame struct {
	StartGame *StartGamePayload `protobuf:"bytes,4,opt,name=start_game,json=startGame,proto3,oneof"`
}

type Message_GetHistory struct {
	GetHistory *GetGameHistoryPayload `protobuf:"bytes,5,opt,name=get_history,json=getHistory,proto3,oneof"`
}

type Message_NewLobbyAvailable struct {
	NewLobbyAvailable *NewLobbyAvailableEvent `protobuf:"bytes,6,opt,name=new_lobby_available,json=newLobbyAvailable,proto3,oneof"`
}

type Message_PlayerJoined struct {
	PlayerJoined *PlayerJoinedLobbyEvent `protobuf:"bytes,7,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

func (*Message_CreateLobby) isMessage_Payload() {}

func (*Message_JoinLobby) isMessage_Payload() {}

func (*Message_StartGame) isMessage_Payload() {}

func (*Message_GetHistory) isMessage_Payload() {}

func (*Message_NewLobbyAvailable) isMessage_Payload() {}

func (*Message_PlayerJoined) isMessage_Payload() {}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\x04dtos\"5\n" +
	"\x12CreateLobbyPayload\x12\x1f\n" +
	"\vmax_players\x18\x01 \x01(\x05R\n" +
	"maxPlayers\"-\n" +
	"\x10JoinLobbyPayload\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\"-\n" +
	"\x10StartGamePayload\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\"4\n" +
	"\x15GetGameHistoryPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\x92\x01\n" +
	"\x16NewLobbyAvailableEvent\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\x05R\n" +
	"maxPlayers\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\x03R\x06hostId\x12#\n" +
	"\rhost_username\x18\x04 \x01(\tR\fhostUsername\"y\n" +
	"\x16PlayerJoinedLobbyEvent\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12'\n" +
	"\x0fplayer_username\x18\x03 \x01(\tR\x0eplayerUsername\"\xc1\x03\n" +
	"\aMessage\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.dtos.MessageTypeR\x04type\x12=\n" +
	"\fcreate_lobby\x18\x02 \x01(\v2\x18.dtos.CreateLobbyPayloadH\x00R\vcreateLobby\x127\n" +
	"\n" +
	"join_lobby\x18\x03 \x01(\v2\x16.dtos.JoinLobbyPayloadH\x00R\tjoinLobby\x127\n" +
	"\n" +
	"start_game\x18\x04 \x01(\v2\x16.dtos.StartGamePayloadH\x00R\tstartGame\x12>\n" +
	"\vget_history\x18\x05 \x01(\v2\x1b.dtos.GetGameHistoryPayloadH\x00R\n" +
	"getHistory\x12N\n" +
	"\x13new_lobby_available\x18\x06 \x01(\v2\x1c.dtos.NewLobbyAvailableEventH\x00R\x11newLobbyAvailable\x12C\n" +
	"\rplayer_joined\x18\a \x01(\v2\x1c.dtos.PlayerJoinedLobbyEventH\x00R\fplayerJoinedB\t\n" +
	"\apayload*\xaa\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x14\n" +
	"\x10GET_GAME_HISTORY\x10\x01\x12\x14\n" +
	"\x10GET_GAME_LOBBIES\x10\x02\x12\x10\n" +
	"\fCREATE_LOBBY\x10\x03\x12\x0e\n" +
	"\n" +
	"JOIN_LOBBY\x10\x04\x12\x0e\n" +
	"\n" +
	"START_GAME\x10\x05\x12\x17\n" +
	"\x13NEW_LOBBY_AVAILABLE\x10\x06\x12\x17\n" +
	"\x13PLAYER_JOINED_LOBBY\x10\aB\bZ\x06./dtosb\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_messages_proto_goTypes = []any{
	(MessageType)(0),               // 0: dtos.MessageType
	(*CreateLobbyPayload)(nil),     // 1: dtos.CreateLobbyPayload
	(*JoinLobbyPayload)(nil),       // 2: dtos.JoinLobbyPayload
	(*StartGamePayload)(nil),       // 3: dtos.StartGamePayload
	(*GetGameHistoryPayload)(nil),  // 4: dtos.GetGameHistoryPayload
	(*NewLobbyAvailableEvent)(nil), // 5: dtos.NewLobbyAvailableEvent
	(*PlayerJoinedLobbyEvent)(nil), // 6: dtos.PlayerJoinedLobbyEvent
	(*Message)(nil),                // 7: dtos.Message
}
var file_proto_messages_proto_depIdxs = []int32{
	0, // 0: dtos.Message.type:type_name -> dtos.MessageType
	1, // 1: dtos.Message.create_lobby:type_name -> dtos.CreateLobbyPayload
	2, // 2: dtos.Message.join_lobby:type_name -> dtos.JoinLobbyPayload
	3, // 3: dtos.Message.start_game:type_name -> dtos.StartGamePayload
	4, // 4: dtos.Message.get_history:type_name -> dtos.GetGameHistoryPayload
	5, // 5: dtos.Message.new_lobby_available:type_name -> dtos.NewLobbyAvailableEvent
	6, // 6: dtos.Message.player_joined:type_name -> dtos.PlayerJoinedLobbyEvent
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	file_proto_messages_proto_msgTypes[6].OneofWrappers = []any{
		(*Message_CreateLobby)(nil),
		(*Message_JoinLobby)(nil),
		(*Message_StartGame)(nil),
		(*Message_GetHistory)(nil),
		(*Message_NewLobbyAvailable)(nil),
		(*Message_PlayerJoined)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		EnumInfos:         file_proto_messages_proto_enumTypes,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
